### ISSUE TITLE
Add 1.0.1 to bower

### ISSUE THREAD

**Issue by vigyanhoon** [DlhSoftTeam/Angular-Kanban#4]
Hi,

Installing component via bower doesn't give latest version of the library i.e. 1.0.1
bower install http://DlhSoft.com/Packages/DlhSoft.KanbanLibrary.zip

Can you please add latest version to bower?

**Comment by DlhSoftTeam** [comment]
NuGet, Bower (ZIP) and NPM (TAR) packages are now updated too.
